### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by th0m4s** [MultiChain/multichain-explorer#16]
Hello,
I've juste created my multichain and it's multichain-explorer, but I got this error when I click on the chain name : 
[Errno socket error] [Errno 111] Connection refused

What can I do? 
Thank you in advance

**Comment by jzakotnik** [comment]
Did you enter the right rpc user/password and allowed the IP to connect?

**Comment by javautil** [comment]
I am having the same issue.  I looked at your docs and I don't wee where I am supposed to set 
my rpc user/password.  I can connect from another multichain mode

my conf file is as follows:

# Config file for MultiChain Explorer
#
# Same file format as Abe.  Please refer to Abe.conf for more
# information about the parameters shown below and other advanced options.

# Port to serve web pages
port 2750

# Who to accept connections from.
# You can only have one host entry in the config file otherwise the explorer will report an error.
# host 0.0.0.0 		# to accept connections from anybody (including localhost) e.g. production
# host localhost 	# to only accept connections from your local machine e.g. testing
host 0.0.0.0

# Configure a MultiChain network
datadir += [{
        "dirname": "~/.multichain/digital-cert-master",              # Path to chain's data folder
        "loader": "default",                            # Do not change
        "chain": "digital certificates",                      # Display name in explorer
        "policy": "MultiChain"                          # Do not change
        }]

# Database type (do not change)
dbtype = sqlite3

# Filename of database
connect-args = digital-cert-master.explorer.sqlite

**Comment by javautil** [comment]
I have a username and pssword in multichain.conf

rpcuser=multichainrpc
rpcpassword=Dt5H7rHiwrRzA1PeNotMyRealPassword

**Comment by jzakotnik** [comment]
Did you set the rpcallowip parameter in the multichain.conf?

**Comment by javautil** [comment]
Now I have, still doesn't work

rpcuser=multichainrpc
rpcpassword=Ah5akDxt9THa9RbyrdxVEXETX34LXSF4Z4zNZhrrdMjn
rpcallowip=10.0.2.0/255.255.0.0
rpcallowip=192.168.56.103/255.255.255.0

**Comment by javautil** [comment]
with 
rpcuser=multichainrpc
rpcpassword=Ah5akDxt9THa9RbyrdxVEXETX34LXSF4Z4zNZhrrdMjn
rpcallowip=10.0.2.0/255.255.0.0
rpcallowip=192.168.56.103/255.255.255.0

I get
[Errno socket error] [Errno 111] Connection refused


with :
rpcuser=multichainrpc
rpcpassword=Ah5akDxt9THa9RbyrdxVEXETX34LXSF4Z4zNZhrrdMjn
rpcallowip=10.0.2.0/255.255.0.0
rpcallowip=192.168.56.103/255.255.255.0
rpcport=9719

I get
RPC failed: ('http protocol error', 0, 'got a bad status line', None)

**Comment by javautil** [comment]
This message will show up if you don't have
rcpport in multichain.conf

or

if the specified port is the default-network-port in params.dat which is the "port" show in getinfo.

Hope that helps

**Comment by th0m4s** [comment]
Thanks for your answer, but where can I view the port in getinfo?

**Comment by th0m4s** [comment]
I've found :)

The explorer can connect to the chain if I add a rcpport in the multichain.conf
